name: checks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - name: Install shellcheck and shfmt
        run: |
          sudo apt-get update -q
          sudo apt-get install -y -q shellcheck shfmt

      - name: Validate manifests and scripts
        run: make check
